/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * CivicPlusChallenge
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  Event,
  EventApiResponse
} from '../../models';





export type postEventsResponse200 = {
  data: EventApiResponse
  status: 200
}

export type postEventsResponseSuccess = (postEventsResponse200) & {
  headers: Headers;
};
;

export type postEventsResponse = (postEventsResponseSuccess)

export const getPostEventsUrl = () => {




  return `http://localhost:7190/Events`
}

export const postEvents = async (event: Event, options?: RequestInit): Promise<postEventsResponse> => {

  const res = await fetch(getPostEventsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      event,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postEventsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postEventsResponse
}




export const getPostEventsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEvents>>, TError,{data: Event}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postEvents>>, TError,{data: Event}, TContext> => {

const mutationKey = ['postEvents'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postEvents>>, {data: Event}> = (props) => {
          const {data} = props ?? {};

          return  postEvents(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostEventsMutationResult = NonNullable<Awaited<ReturnType<typeof postEvents>>>
    export type PostEventsMutationBody = Event
    export type PostEventsMutationError = unknown

    export const usePostEvents = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEvents>>, TError,{data: Event}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postEvents>>,
        TError,
        {data: Event},
        TContext
      > => {
      return useMutation(getPostEventsMutationOptions(options), queryClient);
    }
