/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * CivicPlusChallenge
 * OpenAPI spec version: 1.0
 */
import type { Event } from './event';

export interface GetEventResponse {
  total?: number;
  /** @nullable */
  items?: Event[] | null;
}
