/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * CivicPlusChallenge
 * OpenAPI spec version: 1.0
 */

export type GetEventsParams = {
$top?: number;
$skip?: number;
$filter?: string;
$orderBy?: string;
};
