/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * CivicPlusChallenge
 * OpenAPI spec version: 1.0
 */
import type { GetEventResponse } from './getEventResponse';

export interface GetEventResponseApiResponse {
  data?: GetEventResponse;
  /** @nullable */
  error?: string | null;
  statusCode?: number;
  readonly isSuccess?: boolean;
}
